Output/pjrcUSB/output_com.c

fixes #15 
Could also just call `Output_flushBuffers` there if appropriate.

clear buffers on Consumer/System Control release

---

Debug/cli/cli.c
Debug/cli/cli.h

Sometimes it would be nice to clear the screen if it has a lot of
information (ex: when in debug information). Some terminals support ^L
to clear screen, but not all (iTerm2 on my mac does not), so I think
this is worthwhile to add.

Add Clear CLI function

---

Debug/cli/cli.c

* Use existing logic to avoid processing blank lines as commands so that blank lines don't get put in command history
* Allow CR or LF to be used as enter instead of just CR
* Fixed typo

Avoid putting blank entries in history, allow linefeed for enter

---

Keyboards/cmake.bash

The compilation process itself doesn't take very long, but it's weird to let it continue trying to build when we've encountered an error worthy of changing cmake/make's return codes. This gives clear indication of a failed build as the last line of the script's output.
There are probably more elegant and bash-y ways of doing this and keeping to DRY; let me know if you'd rather I do a larger refactoring.

Exit quickly when cmake or make fail

---

Debug/cli/cli.c

Previously the command was being modified in place in order
to find the command name. This was happening before saving
to the history.
Fixes #70

Write whole debug cli command to history

---

Scan/ISSILed/exampleAPI.bash
Scan/STLcd/bitmap2Struct.py
Scan/STLcd/exampleAPI.bash

The example scripts include hardcoded values that
do not work for everyone. Instead of requiring the
files to be edited (and dirtying the git tree),
allow them to take command-line arguments.
Also adds better guidance for Mac OSX virtual
serial ports.

Stop requiring editing of example scripts

---

buildall.bash

In situations where `ls` colors directories incorrectly, the `$module`
variable contains unprintable characters. This causes directories to be
impossible to `cd` into normally, and is generally a pain.

Ensure directories can only be made with printable characters

---

Macro/PartialMap/macro.c

Nothing too exciting here, just switched from using uint8_t's to var_uint_t's so that when you have more than 254 macros, you can specify stateWordSize to 16 bits and everything works.

Fix a handful of infinite loops that occur with more than 254 macros

---

Keyboards/.gitignore

Ignore all the default BuildPath directories created by the bash scripts via cmake.bash.
---
This is pretty minor, just wanted to clean up my git-status output.
I added this to `Keyboards/.gitignore`, you may prefer to add this to the `.gitignore` at the root of the project.
Also, it might be simpler to just make a `Keyboards/build` directory to contain all the output directories and ignore that instead.

Ignore BuildPath directories

---

Macro/PartialMap/macro.c

This addresses issue #66 and resolves that issue. Now, I cannot use layer shifts to cause a layer to be stuck on.

Added logic to avoid layer shifts causing a layer to be stuck on

---

Dockerfile
Scan/STLcd/lcd_scan.c

I used the caps-lock feature in https://github.com/kiibohd/controller/issues/117 for about a day, and left a bit dissatisfied that the layout maintains its own caps-lock state which can get out of sync with the host. This is a first and kinda sloppy pass at a better way of exposing caps-lock status through the LCD module.
On every scan interval, it grabs the caps lock state from the `USBKeys_LEDs` variable, and determines if caps-lock is coming on or turning off. If it's turning on, it stores the existing backlight color register values. If it's turning off, it restores the saved color registers. If caps-lock is on, it plugs a hard-coded "Fanta Purple" color in to those registers on every scan, with the goal that it'll clobber layer-caused changes to the backlight pretty quickly (I can …

Caps-lock controls LCD backlight

---

Output/pjrcUSB/arm/usb_keyboard.c

`usb_resume()` already checks whether the host is in suspend against a flag set by the ISR, which is enough to decide whether to send a wakeup event or not. Doing it only when allocating fails means you have to fill up the TX queue by pressing 4 keys, and that's incredibly annoying.

Always attempt a USB resume

---

Output/pjrcUSB/arm/usb_dev.c
Output/pjrcUSB/arm/usb_dev.h
Output/pjrcUSB/arm/usb_keyboard.c

The key press used to resume seems to "fall through" and make it to whatever application was focused when the system was put to sleep, drop the packet to prevent that.
Might be related to #75.

Drop packet upon wakeup

---

Output/pjrcUSB/arm/usb_dev.c

More USB resume stuff.
This is a strange edge case I've seen on my system, which seems related to DRAM setup on the host, but that's pretty irrelevant here. What happens is that during bootup, transitions from kernel to kernel (ie UEFI => refind => Linux) or resume from S3, the USB controller stops sending SOFs, misleading the firmware into thinking that we went back to sleep. Since we don't get a resume signal after this condition but the controller resumes normal operation, sending more resume signals at this point can cause weird behavior. It's safe to assume SOF = awake (that's what the USB spec says anyway), so this fixes it.  
I haven't been able to reproduce this behavior with other HIDs.
Hopefully resume should be fully ironed out now, I'll come back with more stuff if I come …

Consider the system awake while we're receiving SOF tokens

---

Keyboards/README.markdown
Keyboards/ergodox.bash
Keyboards/infinity.bash
Keyboards/infinity_led.bash
Keyboards/template.bash
Keyboards/whitefox.bash

The online configurator still mentions the MD1 and MD1.1 names, while master
only talks about 'Infinity 60%' and 'Infinity 60% with LED backlight
support'. Try to avoid confusion by mentioning both names, both in the
README as in the build scripts.
---
I lost some time due to having created my custom layout based on IC60 while I should have used IC60_LED. It was not fully clear how these mapped onto the names used in the online configurator.

Mention MD1/MD1.1 names in addition to 'Infinity 60%'

---

Scan/STLcd/lcd_scan.c

added a separate function to handle datastreams.
handle `lcdCmd <cmd> <a0>` rather then ignoring it.
Signed-off-by: Joshua Schmid <jschmid@suse.de>

create datastream handler and process a0 bit.

---

Scan/Devices/ISSILed/i2c.c

- This makes it possible for the later sequence comparisons to work
- Does not make reading quite functional as there are other issues preventing it

Fix the type of the element

---

Keyboards/README.markdown

The nested list shows up as a blob, and each item is labelled `2.`; adding an extra whitespace line allows it to be rendered properly.

Fix indentation of nested list

---

Bootloader/CMakeLists.txt
Lib/CMake/FindCtags.cmake
Lib/CMake/FindDFUSuffix.cmake
Lib/CMake/buildinfo.cmake
Lib/CMake/modules.cmake

Improve somewhat the support for building on non-Linux systems, such as FreeBSD. To do that, don't assume that ctags is exuberant ctags, and don't assume that any system that isn't macOS or Cygwin is Linux.

Better support for non-Linux systems

---

Lib/nRF5_SDK/external/lwip/src/netif/ppp/eap.c

This is an automatically generated security fix for a vulnerability detected in your code which is a variant of [CVE-2020-8597](https://nvd.nist.gov/vuln/detail/CVE-2020-8597). 
You can read in more detail about this vulnerability in [CERT Advisory VU#782301](https://kb.cert.org/vuls/id/782301/).
The vulnerability occurs because, given that `vallen` was checked to be less than `len`, it can never be the case that `vallen >= len + sizeof(rhostname)`. Therefore, `rhostname` never gets trimmed and the `rhostname` array may overflow.
While this PR was generated for your project automatically, the supporting analysis was performed and verified by the [GitHub Security Lab](https://securitylab.github.com/). 
The original finding was reported by Ilja Van Sprundel from IOActive.
The proposed patch …

[SECURITY] Prevent `rhostname` array overflow

---

Macro/PartialMap/trigger.c

There is a small typo in Macro/PartialMap/trigger.c.
Should read `sequence` rather than `seqence`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, seqence -> sequence
